#include "cg_local.h"

typedef struct
{
	const char* cvarName;
	const char* description;
} cvarDescriptionTable_t;

static cvarDescriptionTable_t cvarDescriptionTable[] =
{
	/*
	    -=useless=-
	{ "osp_print_issues", "^1Useless command" },
	{ "osp_debug", "^1Useless command" },
	{ "cg_forceModel", "Force models.\n^1Useless command" },
	{ "cg_forceColors", "Force colors.\n^1Useless command" },
	{ "cg_useScreenShotJPEG", "^6Probably useless" },
	{ "cg_drawDecals", "^6Probably useless" },

	    -=don't need description=-
	{ "osp_client", "Client version" },
	{ "cg_swingSpeed", "Controls the speed at which the player model's torso and legs smoothly rotate to match movement direction.\n Higher values make the transition faster; lower values result in slower, more gradual turning." },
	{ "cg_animspeed", " " },
	{ "cg_debuganim", " " },
	{ "cg_debugposition", "^5Cheat protected^7\n Lol. Set ^20^7 to disable." },
	{ "cg_debugevents", "^5Cheat protected^7\nPrint events. Set ^20^7 to disable." },
	{ "snaps", " " },

	    -=i dunno how it works=-
	{ "cg_timescaleFadeEnd", " " },
	{ "cg_timescaleFadeSpeed", " " },

	{ "ch_weaponList", "^1Not working" },
	{ "ch_weaponListBackground", "^1Not working" },
	{ "ch_weaponListDrawAll", "^1Not working" },
	{ "ch_weaponListFlash", "^1Not working" },
	*/
	{ "cg_autoAction", "Automatically performs actions at certain points in the game. Bitmask:\n  1 - Save stats to a local text file at the end of a match.\n  2 - End-level screenshot\n  4 - Automatically records a match\n  8 - Team's weapon stats\n  16 - All players' weapon stats" },
	{ "cg_enemyModel", "Select model for enemies. Use ^2/pm^7 (e.g. Sarge/pm) models to apply enemy colors." },
	{ "cg_autoswitch", "Automatically switches to the picked-up weapon. Set ^20^7 to disable autoswitching." },
	{ "cg_drawGun", "First person view weapon appearence. Bitmask:\n  ^20^7 - hidden\n  ^21^7 - default\n  ^22^7 - no movement animation\n  ^23^7 - qlive style (preset, not bitmask)\n  ^24^7 - no switch animation\n  ^28^7 - no fire animation\n  ^216^7 - ghost shader" },
	{ "cg_zoomfov", "Field of view while zooming - degrees" },
	{ "cg_zoomTime", "Zooming time - milliseconds" },
	{ "cg_zoomSensitivityAuto", "Mouse sensitivity mode during zoom\n  ^20^7 - manual\n  ^21^7 - automatic" },
	{ "cg_zoomSensitivityMultiplier", "Sensitivity multiplier during zoom for ^3cg_zoomSensitivityAuto ^21^7" },
	{ "cg_fov", "Field of view - degrees" },
	{ "cg_viewsize", "Size of the game view - percentage" },
	{ "cg_stereoSeparation", "3D stereo separation level" },
	{ "cg_gibs", "Sets the display of animated explosions and flying body parts. Set ^20^7 to disable gibs.\n  ^21^7 - enabled\n  ^22^7 - more blood and gibs" },
	{ "cg_draw2D", "Displays 2D HUD elements. Set ^20^7 to disable." },
	{ "cg_drawStatus", "Show player status information. Set ^20^7 to hide." },
	{ "cg_drawTimer", "Show match timer\n  ^20^7 - disabled\n  ^21^7 - enabled\n  ^22^7 - draw in center" },
	{ "cg_drawFPS", "Show frames per second counter. Set ^20^7 to hide." },
	{ "cg_drawSnapshot", "Show render snapshot info. Set ^20^7 to hide." },
	{ "cg_draw3dIcons", "Display 3D icons on the HUD. Set ^20^7 to disable." },
	{ "cg_drawIcons", "Draw icons on the HUD. Set ^20^7 to disable." },
	{ "cg_ammoCheck", "Disables the ability to switch to a weapon that doesn't have any ammo (^6?^7)" }, // not sure
	{ "cg_drawAmmoWarning", "Show ammo warning indicator. Set ^20^7 to hide.\n  ^21^7 - new counting system\n  ^22^7 - old(default)" },
	{ "cg_drawAttacker", "Display last attacker information. Set ^20^7 to hide." },
	{ "cg_drawCrosshair", "Select crosshair\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairGauntlet", "Select crosshair for Gauntlet\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairMachinegun", "Select crosshair for Machinegun\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairShotgun", "Select crosshair for Shotgun\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairGrenadeLauncher", "Select crosshair for Grenade Launcher\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairRocketLauncher", "Select crosshair for Rocket Launcher\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairLightning", "Select crosshair for Lightning\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairRailgun", "Select crosshair for Railgun\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairPlasmagun", "Select crosshair for Plasmagun\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_drawCrosshairBFG", "Select crosshair for BFG\n  ^20^7 - none\n  ^21^7, ^22^7, ^23^7... - different crosshairs." },
	{ "cg_crosshairSize", "Select crosshair size." },
	{ "cg_crosshairAspectRatioFix", "Enables crosshair aspect ratio correction. Set ^20^7 to disable." },
	{ "cg_crosshairHealth", "Colorize crosshair by health levels. Set ^20^7 to disable." },
	{ "cg_crosshairX", "Adjust horizontal crosshair position." },
	{ "cg_crosshairY", "Adjust vertical crosshair position." },
	{ "cg_brassTime", "Duration for shell casings to remain visible - milliseconds." },
	{ "cg_simpleItems", "Sets the display of items\n  ^20^7 - 3D animated\n  ^21^7 - items drawn as sprites\n  ^22^7 - sprites are slightly raised" },
	{ "cg_marks", "Shows weapon impact marks on walls and floors. Set ^20^7 to disable." },
	{ "cg_lagometer", "Draws the \"lag\" a player feels (network and rendering) in real time\n  ^20^7 - disabled\n  ^21^7 - Show in right bottom\n  ^22^7 - Show in right top" },
	{ "cg_railTrailTime", "Railgun trail display duration - milliseconds." },
	{ "cg_gunX", "Adjust the first-person weapon's forward/backward position." },
	{ "cg_gunY", "Adjust the first-person weapon's horizontal position." },
	{ "cg_gunZ", "Adjust the first-person weapon's vertical position." },
	{ "cg_centertime", "Center text fading delay - milliseconds." },
	{ "cg_runpitch", "Set amount of vertical bobbing while running.  ^20^7 to disable." },
	{ "cg_runroll", "Set mount of side-to-side rolling while running.  ^20^7 to disable." },
	{ "cg_bobup", "Set amount of vertical bobbing while walking.  ^20^7 to disable." },
	{ "cg_bobpitch", "Set amount of forward/backward bobbing while walking.  ^20^7 to disable." },
	{ "cg_bobroll", "Set amount of side-to-side rolling while walking.  ^20^7 to disable." },
	{ "cg_errorDecay", "Applies exponential decay to predicted position errors.\nValue defines decay time in milliseconds.\nSet to 0 to disable smoothing." },
	{ "cg_nopredict", "Disable movement predict. Set ^20^7 to enable predict." },
	{ "cg_noplayeranims", "Disable player animations\n  ^20^7 - animations enabled\n ^21^7 - animations disabled" },
	{ "cg_showmiss", "Print predict misses. Set ^20^7 to disable." },
	{ "cg_footsteps", "Footsteps sound. Set ^20^7 to disable footspets sound." },
	{ "cg_tracerchance", "Tracer chance for Machinegun and Shotgun - percentage (^20^7-^21^7)" },
	{ "cg_tracerwidth", "Tracer width." },
	{ "cg_tracerlength", "Tracer length." },
	{ "cg_predictItems", "Predict pick-up items. Set ^20^7 to disable predict." },
	{ "cg_deferPlayers", "^1Useless command" },
	{ "cg_drawTeamOverlay", "Draw team overlay. Requires ^3cg_enableOSPhud^7 ^21^7\n  ^20^7 - disabled\n  ^22^7 - enabled, left bottom\n  ^23^7 - enabled, right bottom" },
	{ "cg_stats", "Print client frame. Set ^20^7 to disable." },
	{ "com_blood", "Draw gibs and blood(when hit player). Set ^20^7 to disable." },
	{ "g_synchronousClients", "Used for accurate demo recording or debugging. Forces all player movement to be driven directly by the server.\nSet ^20^7 to disable." },
	{ "cg_thirdPerson", "Enable third person view. Use ^3cg_cameraOrbit^7 to enable rotation.\nSet ^20^7 for first person view." },
	{ "cg_thirdPersonRange", "Third person camera distance." },
	{ "cg_thirdPersonAngle", "Third person camera angle." },
	{ "cg_cameraOrbit", "Third-person camera orbit speed. Value > ^20^7 enables rotation. Requires ^3cg_thirdPerson^7 ^21^7." },
	{ "cg_cameraOrbitDelay", "Rotating delay in milliseconds. Requires ^3cg_thirdPerson^7 ^21^7." },
	{ "cg_scorePlums", "Toggles the display of the floating scoring number balloons when a player scores a (negative) point or points in any game type. The awarded point value floats up from the target like a balloon and slowly fades out.\nSet ^20^7 to disable." },
	{ "cg_smoothClients", "Smooth movement of other players by interpolating between snapshots.\n  ^20^7 - disabled (more accurate but jittery)\n  ^21^7 - enabled (smoother visuals)" },
	{ "com_cameraMode", "Choose camera mod for ^3cg_thirdperson^7\n  ^20^7 - show player\n  ^21^7 - hide player" },
	{ "pmove_fixed", "Enable fixed movement sampling rate independent of framerate\n  ^20^7 - use variable framerate sampling (default)\n  ^21^7 - fixed sampling (smoother and more predictable input). May be allowed by server." },
	{ "pmove_msec", "Sets the waiting time in milliseconds before calling pmove() again. Can only be used when ^3pmove_fixed^7 is ^21^7" },
	{ "cg_noTaunt", "Disable gesture animation and sound. Set ^20^7 to enable taunt/gesture." },
	{ "cg_noProjectileTrail", "Disable projectile trails (Rocket/Grenade/OldPlasma). Set ^20^7 to enable trails." },
	{ "cg_oldRail", "Select old rail trail style. Set ^20^7 to select Quake 3 Arena style." },
	{ "cg_oldRocket", "Enable old rocket boom style. Set ^20^7 to select Quake 3 Arena style." },
	{ "cg_oldPlasma", "Enable old plasma trail style\n  ^20^7 - new plasma trail\n  ^21^7 - old plasma trail" },
	{ "cg_altGrenades", "Make grenades more brighter. Set ^20^7 to use default grenades." },
	{ "cg_altLightning", "Choose alternate lightning gun beam. Using shaders ^9lightningBoltNew3^7..^9lightningBoltNew15 and ^9lightningBoltNewNoPicMip3^7..^9lightningBoltNewNoPicMip15^7\n  0 - default beam\n  1...15 - custom beams" },
	{ "cg_clientLog", "Enables client-side logging option. A non-zero value of 'X' (where 'X' is 1 or higher) enables logging all of messages issued during gameplay. All entries are appended to osp/client_logs/clientX.txt text file." },
	{ "cg_crosshairPulse", "Crosshair pulse on item pickup. Set ^20^7 to disable." },
	{ "cg_customLoc", "Use custom location names instead of default ones. Locs stored in osp/locs.\nSet ^20^7 to disable." },
	{ "cg_damageSound", "Play sound feedback when receiving damage. Set ^20^7 to disable." },
	{ "cg_damageDraw", "Show visual indicators when taking damage\n  0 - disabled\n  1 - enabled\n  2 - ratmod damage indicator " },
	{ "cg_damageIndicatorScale", "Scale factor for damage indicator size - ^20.0^7 - ^22.0^7" },
	{ "cg_damageIndicatorOpaque", "Opacity level of damage indicators - ^20.0^7 - ^21.0^7" },
	{ "cg_damageKick", "Screen kick when taking damage. Set ^20^7 to disable shaking." },
	{ "cg_deadBodyFilter", "Filter out (hiding) dead player bodies. Set ^20^7 to show dead bodies." },
	{ "cg_deadBodyInvisible", "Make dead bodies fully invisible. Set ^20^7 to make bodies visible." },
	{ "cg_drawPing", "Show ping (latency) on HUD. Requires ^3cg_enableOSPhud^7 ^21^7\nSet ^20^7 to hide ping." },
	{ "cg_enableOSPHUD", "Enable OSP-style HUD instead of default HUD. Set ^20^7 to disable OSP HUD." },
	{ "cg_shud", "Enables superhud. Set ^20^7 to disable SuperHUD.\nUse ^3ch_file^7 to set configuration file. " },
	{ "cg_enableBreath", "Draw player's breath puff. Set ^20^7 to disable." },
	{ "cg_enemyColors", "Select enemy model(/pm) and rail colors. Settings in ^3cg_enemyModelColors^7 and ^3cg_enemyRailColors^7 overrides this.\nSet 4 Colors in a row. Order: Rail Head Body Legs.\nExapmle: \"^20000^7\", \"^2iqii^7\", or use ^2hex^7." },
	{ "cg_teamColors", "Select team model(/pm) and rail colors. Settings in ^3cg_teamModelColors^7 and ^3cg_teamRailColors^7 overrides this.\nSet 4 Colors in a row. Order: Rail Head Body Legs.\nExapmle: \"^20000^7\", \"^2iqii^7\", or use ^2hex^7." },
	{ "cg_teamModel", "Select model for teammates. Use ^2/pm^7 (e.g. Sarge/pm) models to apply team colors." },
	{ "cg_execVstr", "Specifies a string to exec after connecting to a server.  OSP performs\n'vstr <string>' on the value of this variable.\nHelpful for +zoom scripts for thin-shaft, as an example." },
	{ "cg_fallKick", "Enables camera shake effect when landing from a fall. Set to ^20^7 to disable." },
	{ "cg_followkiller", "Allows client to auto-switch to killer of chased player. Cool for specing in-eyes 1v1 matches, and cool for viewcam player specing in team games.\nSet ^20^7 to disable." },
	{ "cg_followpowerup", "Allows client to auto-follow powerup pickup if spectating. Set ^20^7 to disable." },
	{ "cg_followviewcam", "Toggles use of dynamic or specific player follow mode of the viewcam. Set ^20^7 to disable." },
	{ "cg_lightningImpact", "Draw Lightning beam hit effect. Set ^20^7 to hide." },
	{ "cg_MaxlocationWidth", "Select max width for location names in Team Overlay. Requires ^3vid_restart^7." },
	{ "cg_muzzleFlash", "Show muzzle flash effects when firing weapons. Set ^20^7 to hide muzzle flash." },
	{ "cg_noChatBeep", "Disable beep sound when receiving chat messages. Set ^20^7 to enable sound." },
	{ "cg_noTeamChatBeep", "Disable beep sound for team chat messages. Set ^20^7 to enable sound." },
	{ "cg_NoMOTDDisplayDuringDemo", "Hide Message of the Day when watching demos. Set ^20^7 to show." },
	{ "cg_nomip", "Disable mipmapping for 2D icons\n  ^20^7 - mipmapping enabled\n  ^21^7 - sharp icons" },
	{ "cg_oversampleMouse", "Apply mouse input oversampling for smoother aiming.Set ^20^7 to disable oversampling." },
	{ "cg_statScrollTime", "Scroll time for sliding window (+wstats)" },
	{ "cg_q3compScoreboard", "Use Quake 3-compatible scoreboard layout. Set ^20^7 to disable." },
	{ "cg_scoreTransparency", "Set transparency level for scoreboard background - ^20.0^7 - ^21.0^7" },
	{ "cg_showPlayerLean", "Show player lean animations. Set ^20^7 to disable." },
	{ "cg_smoke_sg", "Draw smoke puff effect for shotgun shots. Set ^20^7 to hide." },
	{ "cg_smokegrowth_gl", "Grenade smoke trail growth speed." },
	{ "cg_smokegrowth_rl", "Rocket smoke trail growth speed." },
	{ "cg_smokeradius_gl", "Grenade smoke trail radius." },
	{ "cg_smokeradius_rl", "Rocket smoke trail radius" },
	{ "cg_smokedensity_gl", "Grenade smoke trail density." },
	{ "cg_smokedensity_rl", "Rocket smoke trail density." },
	{ "cg_swapSkins", "Swap enemy and team model skins. Set ^20^7 to use correct team skins." },
	{ "cg_teamRails", "Use team-colored railgun trails, use ^3cg_teamRailColors ^7and ^3cg_enemyRailColors^7 to set color.\n Set ^20^7 to disable." },
	{ "cg_trueLightning", "Adjust lightning gun shaft lag\n  ^20.0^7 - full lag (baseq3 feel)\n  ^21.0^7 - no lag (shaft follows crosshair)" },
	{ "ch_3waveFont", "Select charset for OSP HUD" },
	{ "ch_ColorLocations", "Colorize location messages. Set ^20^7 to use plain text" },
	{ "ch_crosshairColor", "Select crosshair color.\n \"^2color^7\" - color name, digit or hex" },
	{ "cf_CrosshairNames", "Select crosshair names size. Requires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_CrosshairNamesLeft", "Align crosshair player names to the left. Set ^20^7 to draw names in center." },
	{ "ch_crosshairTeamInfo", "Show team information next to crosshair target. Set ^20^7 to hide." },
	{ "ch_drawHealthMeters", "Display health meters instead of digits on HUD. Requires ^3cg_enableOSPhud^7 ^21^7\nSet ^20^7 for digits." },
	{ "ch_drawFlagNames", "Select draw flag carrier style. Requires ^3cg_enableOSPhud^7 ^21^7.\n  ^20^7 - default\n  ^21^7 - name\n  ^22^7 - name + icon\n  ^23^7 - name, bottom right corner (^3Q3comp^7)\n  ^24^7 - name + icon, bottom right corner (^3Q3comp^7)" },
	{ "ch_drawPickup", "^6Probably useless." },
	{ "ch_drawSpeed", "Display player speed (UPS)\n  0 - hidden\n  1 - top-right\nRequires ^3cg_enableOSPhud^7 ^21^7\n  2 - above crosshair (works with any HUD)" },
	{ "ch_TeamBackground", "Draw teambackground color in statusbar, teamchat. Set ^20^7 to disable." },
	{ "cf_Following", "Following message font size. Requires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_FilterLocationsTeamchat", "Print location near player's name in team chat. Set ^20^7 to disable." },
	{ "ch_fragMessage", "Print message on top of your HUD when you score a frag.\nSet ^20^7 to disabled" },
	{ "ch_file", "Select superhud configuration file\n Put *.cfg file into osp/hud directory\n  \"^2filename^7\"" },
	{ "cf_Fragmsg", "Font size of the \"you fragged\" messages on top of your HUD. Requires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_graphs", "Draw health, armor, and item status bars as colored rectangles on the HUD. Requires ^3cg_enableOSPhud^7 ^21^7.\nSet ^20^7 to disable." },
	{ "ch_InverseTeamChat", "Display team chat messages in reverse order. Set ^20^7 to use default order" },
	{ "ch_Obituaries", "Kill feed messages.\n  ^20^7 - hard disable: all messages are stopped immediately\n  ^21^7 - enabled" },
	{ "ch_Pickupitem", "Display recently picked-up item icon and name on screen. Set ^20^7 to disable." },
	{ "cf_Pickupstring", "Font size of the picked up item. Requires ^3cg_enableOSPhud^7 ^21^7 and ^3ch_Pickupitem^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_recordMessage", "Show demo-record message. Set ^20^7 to disable." },
	{ "cf_Scores", "OSP HUD scores size. Requires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "cf_Statusbar", "OSP HUD status bar size. Requires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_StatusbarFormat", "OSP HUD Status bar format. Requires ^3cg_enableOSPhud^7 ^21^7\n  ^20^7 - default Q3A\n  ^21^7-^212^7 - different formats" },
	{ "ch_statusbarStyle", "^2Not working^7" },
	{ "ch_TeamchatOnly", "Print only team chat messages in console. Set ^20^7 to print all messages." },
	{ "cf_Teamchat", "Font size of the teamchat. Requires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_TeamCrosshairHealth", "Show health and armor of teammates under the crosshair. Set ^20^7 to disable." },
	{ "cf_TeamCrosshairHealth", "Font size of the health and armor of teammates under the crosshair.\nRequires ^3cg_enableOSPhud^7 ^21^7 and ^3ch_TeamCrosshairHealth^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_Teamoverlay", "Defines the layout of the team overlay line.\n  ^2n^7 - Player name (optionally prefixed with a number for width, e.g. ^212n^7). \n  ^2p^7 - Powerup icon\n  ^2h^7 - Health\n  ^2a^7 - Armor\n  ^2w^7 - Ammo icon\n  ^2l^7 - Location" },
	{ "cf_Teamoverlay", "Font size of team overlay strings.\nRequires ^3cg_enableOSPhud^7 ^21^7 and ^cg_drawTeamOverlay^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "cf_Vote", "Font size of the voting message.\nRequires ^3cg_enableOSPhud^7 ^21^7 and ^cg_drawTeamOverlay^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "ch_Weaponswitch", "Select weapon switch style. Set ^20^7 to hide.\n  ^21^7 - id style\n  ^22^7, ^23^7 - vertical, right\n  ^24^7, ^25^7 - vertical, left\n  ^26^7 - CPM style, left\n  ^27^7 - CPM style, right\n  ^28^7 - CPM style, bottom\n  ^29^7 - same as ^21^7, no text" },
	{ "cf_WeaponSwitch", "Size of the weapon switch graphics. Requires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "cf_WeaponName", "Font size of the weapon name for ^3ch_Weaponswitch^2 1^7.\nRequires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "cf_AmmoStatusbar", "Font size of the ammo count for ^3ch_Weaponswitch^2 2^7/^23^7.\nRequires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "cf_timer", "Font size of the game timer.\nRequires ^3cg_enableOSPhud^7 ^21^7\n  Use format ^2width^7x^2height^7" },
	{ "cg_teamChatTime", "Draw time messages from teammates ^3messagemode2. Requires ^3cg_enableOSPhud^7\n  ^21^7 - ^28^7" },
	{ "cg_teamChatHeight", "Number of lines or strings of text that remain on screen in team play chat mode ^3messagemode2. Requires ^3cg_enableOSPhud^7\n  ^21^7 - ^28^7" },
	{ "handicap", "Limit your maximum health and armor to simulate a disadvantage.\n  ^21^7 - ^2100^7" },
	{ "cg_noLeadSounds", "Disables leadership voice announcements in non-team modes. Set ^20^7 to enable sound." },
	{ "cg_fragSound", "Sound played on frag. File must be: ^9sound/feedback/fragSoundN.wav^7, where ^2N^7 is the sound number (e.g. ^9fragSound2.wav^7)\n  ^20^7 - no sound\n  ^21^7 - built-in sound\n  ^22+^7 - custom sounds (not included)\n" },
	{ "cg_lightningHideCrosshair", "Hides crosshair when using lightning gun. Set ^20^7 to draw crosshair." },
	{ "cg_lightningSilent", "Disables hit sound when using lightning gun. Set ^20^7 to enable sound." },
	{ "cg_lightningHide", "Disables lightning gun beam rendering. Set ^20^7 to show beam." },
	{ "cg_delag", "Select rendering mode for shots at predicted positions instead of crosshair target.\nPurely visual; does not affect server hit processing.\n  ^20^7 - disabled\n  ^21^7 - Lightning Gun and Railgun\n  ^22^7 - Lightning Gun only\n  ^24^7 - Railgun only" },
	{ "cg_projectileNudge", "Compensates for lag when rendering rockets/plasma. Renders projectiles slightly ahead, as the server sees them.\n  ^20^7 - disabled\n  ^21^7 - enemy projectiles\n  ^22^7 - own projectiles\n  ^23^7 - both, enemy and own projectiles." },
	{ "cg_hideScores", "Hides the scoreboard for the XQ3E client to prevent double rendering\n  ^20^7 - disabled\n  ^21^7 - enabled" },
	{ "cg_deadBodyBlack", "Dead body color\n  ^20^7 - default\n  ^21^7 - light gray\n  ^22^7 - gray\n  ^23^7 - dark gray" },
	{ "cg_spectGlow", "Highlights players when spectating. Set ^20^7 to disable." },
	{ "cg_spectOrigModel", "Use the original player model in spectator mode. Set ^20^7 to use forced model" },
	{ "cg_hitSounds", "Varying pitch of the hitsound based on damage\n ^2-1^7 - sound off\n  ^20^7 - pitch doesn't change\n  ^21^7 - the higher the damage, the lower the pitch\n  ^22^7 - the higher the damage, the higher the pitch" },
	{ "cg_playersXID", "Add XID based on player's configuration to their nickname. Requires ^3vid_restart^7\n  ^20^7 - off\n  ^21^7 - always add\n  ^22^7 - add only for duplicate or empty nicknames." },
	{ "cg_playersID", "Add client number in square brackets to player's nickname. Requires ^3vid_restart^7\n  ^20^7 - off\n  ^21^7 - always add [clientNum] before name\n  ^22^7 - add only for duplicate or empty nicknames" },
	{ "cg_playerModelColors", "Set your player model(/pm) colors. Set 3 Colors in a row. Order: Head Body Legs.\nExample: \"^2444^7\", \"^2qqq^7\", or use ^2hex^7." },
	{ "cg_playerRailColors", "Set your rail colors. Write 2 colors in a row. Order: Core Rings.\nExample: \"^266^7\", \"^2990099999999^7\"" },
	{ "cg_playerFrozenColor", "Set your frozen color.\n  \"^2color^7\" - color name, digit or hex" },
	{ "cg_teamModelColors", "Set ally player model(/pm) colors. Set 3 Colors in a row. Order: Head Body Legs.\nExample: \"^2444^7\", \"^2qqq^7\", or use ^2hex^7." },
	{ "cg_teamRailColors", "Set teammates rail colors. Write 2 colors in a row. Order: Core Rings.\nExample: \"^266^7\", \"^2990099999999^7\"" },
	{ "cg_teamFrozenColor", "Set ally frozen color.\n  \"^2color^7\" - color name, digit or hex" },
	{ "cg_enemyModelColors", "Set enemy player model(/pm) colors. Set 3 Colors in a row. Order: Head Body Legs.\nExample: \"^2444^7\", \"^2qqq^7\", or use ^2hex^7." },
	{ "cg_enemyRailColors", "Set enemy rail colors. Write 2 colors in a row. Order: Core Rings.\nExample: \"^266^7\", \"^2990099999999^7\"" },
	{ "cg_enemyFrozenColor", "Set enemy frozen color.\n  \"^2color^7\" - color name, digit or hex" },
	{ "cg_enemyModelColorsUnique", "Set a unique color for the enemy mode. Bitmask:\n  ^20^7 - disabled\n  ^21^7 - head\n  ^22^7 - torso\n  ^24^7 - legs" },
	{ "cg_teamFrozenFoe", "Show snowflake icon for frozen players in freezeTag mode. Set ^20^7 to draw default foe." },
	{ "cg_chatEnable", "Console chat message display mode: ^20^7 - off\n  ^21^7 - global messages enabled\n  ^22^7 - team messages enabled\n  ^23^7 - global and team messages enabled" },
	{ "cg_shudChatEnable", "SuperHUD chat message display mode: ^20^7 - off\n  ^21^7 - global messages enabled\n  ^22^7 - team messages enabled\n  ^23^7 - global and team messages enabled" },
	{ "cg_healthMid", "Yellow color trigger level.\nRequires ^3cg_healthColorLevels^7 ^21^7" },
	{ "cg_healthLow", "Red color trigger level.\nRequires ^3cg_healthColorLevels^7 ^21^7" },
	{ "cg_healthColorLevels", "Activate custom health/armor color change levels. \nConfigure with ^3cg_healthLow^7 and ^3cg_healthMid^7.\n  0 - disabled\n  ^21^7 - enabled\n  ^22^7 - enabled, except team foe" },
	{ "ch_crosshairDecor", "Select crosshair decoration. Set ^20^7 to disable.\n  ^21^7 - ^234^7 - select decor" },
	{ "ch_crosshairDecorSize", "Set size of crosshair decoration." },
	{ "ch_crosshairDecorColor", "Color for crosshair decoration\n \"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshair45", "Rotates the crosshair by 45 degrees. Set ^20^7 to disable." },
	{ "ch_crosshairDecor45", "Rotates the crosshair decoration by 45 degrees. Set ^20^7 to disable." },
	{ "ch_crosshairDecorOpaque", "Crosshair decoration visibility.\n  ^20^7 - ^21^7 (reversed)" },
	{ "ch_crosshairOpaque", "Crosshair visibility.\n  ^20^7 - ^21^7 (reversed)" },
	{ "ch_crosshairAction", "Adds effects to the crosshair. Bitmask:\n  ^20^7 - off\n  ^21^7 - pulses on hit (Doesn't work if ^3cg_crosshairPulse^7 ^21^7)\n  ^22^7 - invisible, but appears on hit\n  ^24^7 - changes color on hit\n  ^28^7 - change color on hit by damage" },
	{ "ch_crosshairActionColor", "Crosshair action color for ^3ch_crosshairAction^7 ^24^7.\n \"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshairActionScale", "Crosshair scaling multiplier on action" },
	{ "ch_crosshairActionTime", "Duration of crosshair action for ^3ch_crosshairAction^7 ^21^7, ^22^7.\n  ^250^7 - ^21000^7 - time in milliseconds" },
	{ "ch_crosshairDecorAction", "Adds effects to the crosshair decoration. Bitmask:\n  ^20^7 - off\n  ^21^7 - pulses on hit\n  ^22^7 - invisible, but appears on hit\n  ^24^7 - changes color on hit\n  ^28^7 - change color on hit by damage" },
	{ "ch_crosshairDecorActionColor", "Crosshair decoration action color for ^3ch_crosshairDecorAction^7 ^24^7.\n \"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshairDecorActionScale", "Crosshair decoration scaling multiplier on action." },
	{ "ch_crosshairDecorActionTime", "Duration of crosshair decoration action for ^3ch_crosshairAction^7 ^21^7, ^22^7.\n  ^250^7 - ^21000^7 - time in milliseconds" },
	{ "ch_crosshairAutoScale", "Automatically scales crosshair size based on distance. Set ^20^7 to disable." },
	{ "cg_dlightGauntlet", "Set the dynamic light color for Gauntlet.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightMG", "Set the dynamic light color for Machinegun.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightSG", "Set the dynamic light color for Shotgun.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightGL", "Set the dynamic light color for Grenade Launcher.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightRL", "Set the dynamic light color for Rocket Launcher.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightLG", "Set the dynamic light color for Lightning Gun.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightRG", "Set the dynamic light color for Railgun.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightPG", "Set the dynamic light color for Plasma Gun.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_dlightBFG", "Set the dynamic light color for BFG.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_gunColor", "Weapon color for ^3cg_drawGun^7 ^23^7.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_gunOpaque", "Weapon visibility for ^3cg_drawGun^7 ^23^7.\n  ^20^7 - ^21^7" },
	{ "cg_conObituaries", "Displays kill/freeze messages in the console. Set ^20^7 to hide." },
	{ "cg_lightningHitsoundRateFix", "Fixes lightning gun hitsound for non-divisible ^4sv_fps^7 settings. Set ^20^7 to disable." },
	{ "cg_stackHitSounds", "Damage stacking for ^3cg_hitsounds^7. Set ^20^7 to disable." },
	{ "cg_stackHitSoundsTimeout", "Clear damage count timeout for ^3cg_stackHitSounds^7 - \"milliseconds\"." },
	{ "cg_drawCenterMessages", "Displays messages in the center of the screen (Welcome message, frag, etc.). Set ^0^7 to hide\n  ^21^7 - draw\n  ^22^7 - draw, with shadow" },
	{ "cg_predictStepOffset", "Smoother step-up movement. Set ^20^7 to disable smoothness. Also fix climbing aim issue." },
	{ "cg_enemyLightningColor", "Lightning gun beam color for enemies\n  ^20^7 - default beam\n \"^2color^7\" - digit or hex" },
	{ "cg_uniqueColorTable", "Unique color table for ^3enemy unique color(s)^7\n  ^21^7 - default\n  ^22^7 - bright" },
	{ "cg_noVoteBeep", "Disables voting beep sound. Set ^20^7 to enable beep sound." },
	{ "cg_damageDrawFrame", "Draws a frame when taking damage. Bitmask:\n  ^20^7 - disabled\n  ^21^7 - gradient fade to center\n  ^22^7 - solid color\n  ^24^7 - draw frame when health is low" },
	{ "cg_damageFrameSize", "Thickness for ^3cg_damageDrawFrame^7\n  ^21^7 - ^2512^7" },
	{ "cg_damageFrameOpaque", "Opacity for ^3cg_damageDrawFrame^7\n  ^20^7 - ^21^7" },
	{ "cg_shud_currentWeapons", "Weapon selection for the SHUD element. Bitmask:\n  ^21^7 - Gauntlet\n  ^22^7 - Machine Gun\n  ^24^7 - Shotgun\n  ^28^7 - Grenade Launcher\n  ^216^7 - Rocket Launcher\n  ^232^7 - Lightning Gun\n  ^264^7 - Railgun\n  ^2128^7 - Plasma Gun" },
	{ "cg_drawHitBox", "Draw hitboxes. Server permission required\n  ^20^7 - disabled\n  ^21^7 - bounding edges\n  ^22^7 -solid color++\n  ^23^7 - solid color" },
	{ "cg_hitBoxColor", "Set color for ^3cg_drawHitBox ^2\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_drawGunForceAspect", "Fix weapon stretching when using 4:3 aspect ratio on widescreen. Set ^20^7 to disable." },
	{ "cg_drawOutline", "Set player outline rendering mode. Use ^3cg_enemyOutline*^7 and ^3cg_teamOutline*^7 to change colors and style.\n  ^20^7 - disabled\n  ^21^7 - enemies only\n  ^22^7 - teammates only\n  ^23^7 - all players" },
	{ "cg_enemyOutlineSize", "Set ^3cg_drawOutline^7 thickness for enemies\n  ^20^7 - disabled\n  ^21^7 - thin\n  ^22^7 - medium\n  ^23^7 - thick" },
	{ "cg_enemyOutlineColor", "Set enemy ^3cg_drawOutline^7 color.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_enemyOutlineColorUnique", "Assigns a unique ^3cg_drawOutline^7 color for enemy model parts. Bitmask:\n  ^20^7 - disabled\n  ^21^7 - head\n  ^22^7 - torso\n  ^24^7 - legs\n  ^27^7 - full model" },
	{ "cg_teamOutlineSize", "Set ^3cg_drawOutline^7 thickness for teammates.\n  ^20^7 - disabled\n  ^21^7 - thin\n  ^22^7 - medium\n  ^23^7 - thick" },
	{ "cg_teamOutlineColor", "Set teammate ^3cg_drawOutline^7 color.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_underwaterFovWarp", "Underwater camera warp effect. Set ^20^7 to disable." },
	{ "cg_altBlood", "Alternative blood effects on model hit\nUses shaders ^6bloodExplosionNew^7, ^6bloodExplosionNew#^7, where # is a number from 2 to 17\n  ^20^7 - disabled, default blood\n  ^21^7-^216^7 for customization" },
	{ "cg_altBloodColor", "Color of blood on model hit.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_altPlasma", "Alternative plasma projectile and trail rendering\n  ^20^7 - disabled\n  ^21^7 - enabled\n  ^22^7 - pre-alpha shader" },
	{ "cg_drawRewards", "Draw rewards (e.g. excellent, impressive etc).\n  ^20^7 - disabled (float sprite enabled)\n  ^21^7 - fully enabled\n  ^22^7 - disable icon on hud\n  ^24^7 - disable float sprite\n  ^28^7 - disable sound" },
	{ "cg_shotGunTracer", "Draw tracer for flying shotgun pellets. Set ^20^7 to disable." },
	{ "cg_railRingsRadius", "Spiral radius ^3oldRail^7 ^20^7\n  ^20.05^7 - ^216^7" },
	{ "cg_railRingsRotation", "Degree of rotation ^3oldRail^7 ^20^7\n  ^20^7 - disabled\n  ^21^7 - default\n  ^22^7 - frequent" },
	{ "cg_railRingsSpacing", "Spiral spacing ^3oldRail^7 ^20^7\n  ^24^7 - ^2128^7" },
	{ "cg_railRingsSize", "Size of the spiral rings ^3oldRail^7 ^20^7\n  ^20.05^7 - ^24^7" },
	{ "cg_railStaticRings", "More static railgun rings ^3oldRail^7 ^20^7. Set ^20^7 to disable." },
	{ "cg_gunPos", "Choose the side for weapon rendering\nSet ^3cg_gunY^7 to ^20^7\n  ^21^7 - right\n  ^22^7 - left\n  ^23^7 - center" },
	{ "cg_shadows", "Sets the shadow detail level.\n -1 - enabled, static\n  0 - disabled\n  1 - enabled\n  2 - stencil buffered\n  3 - simple stencil buffered if ^3r_stencilbits^7 is not ^20^7" },
	{ "cg_altShadow", "Alternative shadow. Uses shaders markShadowNew, markShadowNew#, where # is a number from 2 to 17\n  0 - disabled\n  1-16 for customization. " },
	{ "cg_altShadowColor", "Color of the ^3cg_altShadow^7.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_scoreboardShowId", "Display player IDs on the scoreboard. Set ^20^7 to hide." },
	{ "cg_drawFriend", "Show marker above teammate:\n  ^20^7 - disabled\n  ^21^7 - enabled\n  ^22^7 - frozenFoe only" },
	{ "cg_teamIndicator", "Draw player indicator over ally. Set ^20^7 to disable.\nBitmask:\n  ^21^7 - name\n  ^22^7 - name without effects, set color using ^3cg_teamIndicatorColor^7\n  ^24^7 - HP and AP\n  ^28^7 - frozen info\n  ^216^7 - status icon\n  ^232^7 - spectator mode" },
	{ "cg_teamIndicatorAdjust", "Font scaling for the indicator\n  ^20.5^7 - ^22^7" },
	{ "cg_teamIndicatorColor", "Indicator text color. For ^3cg_teamIndicator ^22^7\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_teamIndicatorOpaque", "Text opacity\n  ^20^7 - ^21^7" },
	{ "cg_teamIndicatorBgColor", "Set background color of the indicator\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_teamIndicatorBgOpaque", "Set background opacity of the indicator\n  ^20^7 - ^21^7" },
	{ "cg_teamIndicatorOffset", "Vertical offset of the indicator\n  ^2-12^7 - ^232^7" },
	{ "cg_teamIndicatorMaxLength", "Maximum allowed length of the player name in the indicator" },
	{ "cg_teamIndicatorFont", "Font selection for team indicator\n  ^20^7 - ^210^7" },
	{ "cg_scoreboardBE", "Enable alternative OSP scoreboard. Set 20^7 to use default scoreboard.\n ^21^7 - proportional font\n  ^22^7 - old style team scores\n  ^24^7 - white colored titles\n  ^28^7 - team colored titles" },
	{ "cg_scoreboardFont", "Font selection for alternative scoreboard\n  ^20^7 - ^210^7" },
	{ "cg_scoreboardScale", "Scale factor for the scoreboard size. ^21.0^7 - default size, higher values make it larger." },
	{ "cg_centerMessagesFont", "Font selection for center messages\n  ^20^7 - ^210^7" },
	{ "cg_drawCrosshairNames", "Display names when crosshair is on target\n  ^20^7 - disabled\n  ^21^7 - enabled\n  ^22^7 - only allies\n  ^23^7 - only enemies" },
	{ "cg_railCustomChamber", "Colorize rail chamber using custom colors. Bitmask:\n  ^20^7 - disabled\n  ^21^7 - reloading using core color\n  ^22^7 - ready to fire using rings color" },
	{ "cg_drawBrightWeapons", "Render weapons with a single bright color for better visibility. Bitmask:\n  ^21^7 - own\n  ^22^7 - teamamtes\n  ^24^7 - enemies\n  ^28^7 - world"},
	{ "cg_altGrenades", "Alternative grenade appearance. Values:\n  ^20^7 - Disabled\n  ^21^7 - OSP style\n  ^22^7 - BE style (custom color)" },
	{ "cg_altGrenadesColor", "Color for alternative grenades. Requires ^3cg_altGrenades^7 set to ^22^7.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_enemyGrenadesColor", "Color for enemy grenades (not supported everywhere). Requires ^3cg_altGrenades^7 set to ^22^7.\n \"^2color^7\" - color name, digit or hex" },
	{ "cg_altBattleSuit", "Alternative battle suit effect:\n  ^20^7 - Disabled\n  ^21^7 - Enabled" },
	{ "cg_itemFx", "Changes how items are rendered in the world. Bitmask:\n  ^20^7 - static\n  ^21^7 - bounce\n  ^22^7 - rotating\n  ^24^7 - scale"},
	{ "cg_bubbleTrail", "Enables the drawing of bubble trails drawn by projectiles entering water. Set ^20^7 to disable."},
	{ "cg_ignoreServerMessages", "Hides the message from server. Bitmask:\n  ^20^7 - show messages\n  ^21^7 - hide killer HP/AP (Q3MSK FFA only)\n  ^22^7 - hide ^1chat fragged^7\n  ^24^7 - hide server's chat-messages"},
	{ "cg_healthColor", "Health/armor color, requires ^3cg_healthColorLevels^7 ^21^7\n \"^2color^7\" - color name, digit or hex"},
	{ "cg_healthLowColor", "Health/armor color when reaching cg_healthLow, requires ^3cg_healthColorLevels^7 ^21^7\n \"^2color^7\" - color name, digit or hex"},
	{ "cg_healthMidColor", "Health/armor color when reaching cg_healthMid, requires ^3cg_healthColorLevels^7 ^21^7\n \"^2color^7\" - color name, digit or hex"},
	{ "cg_redTeamColor", "Set red team color. \"^2color^7\" - color name, digit or hex"},
	{ "cg_blueTeamColor", "Set blue team color. \"^2color^7\" - color name, digit or hex"},
	{ "cg_drawAccuracy", "Draw weapon accuracy in scoreboard. Set ^20^7 to disable.\n  ^21^7 - left\n  ^22^7 - top\n  ^23^7 - right\n  ^24^7 - bottom"},
	{ "cg_accuracyFontSize", "Set font size for weapon accuracy"},
	{ "cg_accuracyIconSize", "Set icon size for weapon accuracy"},
	{ "cg_accuracyFont", "Font selection for weapon accuracy.\n  ^20^7 - ^210^7"},
	{ "ch_crosshairActionColorLow", "Low damage color for crosshair action (used with ^3ch_crosshairDecorAction ^28^7).\n\"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshairActionColorMid", "Medium damage color for crosshair action (used with ^3ch_crosshairDecorAction ^28^7).\n\"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshairActionColorHigh", "High damage color for crosshair action (used with ^3ch_crosshairDecorAction ^28^7).\n\"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshairDecorActionColorLow", "Low damage color for crosshair decorator action (used with ^3ch_crosshairDecorAction ^28^7).\n\"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshairDecorActionColorMid", "Medium damage color for crosshair decorator action (used with ^3ch_crosshairDecorAction ^28^7).\n\"^2color^7\" - color name, digit or hex" },
	{ "ch_crosshairDecorActionColorHigh", "High damage color for crosshair decorator action (used with ^3ch_crosshairDecorAction ^28^7).\n\"^2color^7\" - color name, digit or hex" },
	{ "cg_mySound", "Set player model sound set. \"^2model^7\" - model name, e.g. ^2keel^7" },
	{ "cg_teamSound", "Set teammate model sound set. \"^2model^7\" - model name, e.g. ^2keel^7" },
	{ "cg_enemySound", "Set enemy model sound set. \"^2model^7\" - model name, e.g. ^2keel^7" },
	{ "cg_markTeam", "Mark teammate(s) to change outline color. \"^2-1^7\" disables it. Player IDs separated by spaces, e.g. ^20 3 7^7" },
	{ "cg_markTeamColor", "Outline color for marked teammates. \"^2color^7\" - name, digit or hex" },
	{ "cg_friendHudMarkerMaxDist", "Maximum distance at which the teammate HUD marker is visible. ^20^7 - unlimited." },
	{ "cg_friendHudMarkerSize", "Base size of the teammate HUD marker." },
	{ "cg_friendHudMarkerMaxScale", "Maximum additional scale factor based on distance (applied to base size)." },
	{ "cg_friendHudMarkerMinScale", "Minimum scale factor based on distance." },
	{ "cg_friendsWallhack", "Show teammate markers through walls. Bitmask:\n  ^20^7 - disabled\n  ^21^7 - foe\n  ^22^7 - team indicator" },
	{ "cg_drawHudMarkers", "Whether to display teammate markers on the HUD." },
	{ "cg_scoreboardRtColors", "Color of the red team scoreboard. ^3cg_scoreboardBE^7 must be enabled \n  ^2<color> <color> <color>^7 separated by space. Third argument is optional. For example \"^2Red Green Yellow^7\" or \"^20099FF 99FF00 99FF00^7\" or \"^24 Red 4^7\"." },
	{ "cg_scoreboardBtColors", "Color of the blue team scoreboard. ^3cg_scoreboardBE^7 must be enabled\n  ^2<color> <color> <color>^7 separated by space. Third argument is optional. For example \"^2Red Green Blue^7\" or \"^20099FF 99FF00 20099FF^7\" or \"^24 Red 2^7\"." },
	{ "cg_scoreboardSpecColor", "Color of the spectator scoreboard. ^3cg_scoreboardBE^7 must be enabled\n  ^2<color> <color>^7 separated by space. Second argument is optional" },
	{ "cg_scoreboardDrawPowerUps", "Draw colored frame on scoreboard for players who have active powerups. Set ^20^7 to disable\n  ^21^7 - full frame\n  ^2^7 - left border only" },
	{ "cg_bestats_style", "Style of the battle statistics display.\n  ^21^7 - default\n  ^22^7 - minimized" },
	{ "cg_bestats_textSize", "Size of the battle statistics text. First number is character width, second is height.\n  ^2W H" },
	{ "cg_bestats_font", "Font selection used for battle statistics\n  ^20^7 - ^210^7" },
	{ "cg_bestats_pos", "Position of the battle statistics window on screen\n  ^2X Y'." },
	{ "cg_bestats_bgColor", "Background color of the battle statistics window. Empty value uses the team color\n  ^2<color>^7" },
	{ "cg_bestats_bgOpaque", "Background opacity of the battle statistics window\n  ^20.0^7-^21.0^7" },
	{ "cg_bestats_spacingAdjust", "Line spacing adjustment in the battle statistics window." },
	{ "cg_bestats_widthCutoff", "Width reduction (cutoff) of the battle statistics window." },
	{ "cg_teamIndicatorFade", " Ally indicator transparency level when aiming at a teammate. Set ^20^7 to disable." },
	{ "cg_teamIndicatorFadeRadius", "Radius at which the ally indicator starts fading." },
	{ "be_enabled", "Enable BE features. Set ^30^7 to disable." },
	{ "cg_chud", "Enable CherryHUD system. Set ^20^7 to disable CherryHUD." },
	{ "chud_file", "CherryHUD configuration file name. File must be in the 'chud' directory.\n  \"^2filename^7\"" },
	{ "cg_clearOnLevelLoad", "Clear console when loading a new level. Set ^20^7 to disable." },
	{ "cg_playersID", "Add client number to player's nickname. Requires ^3vid_restart^7\n  ^20^7 - off\n  ^21^7 - always add [clientNum] before name\n  ^22^7 - add only for duplicate or empty nicknames" },
	{ "cg_spectPOV", "Use team perspective when spectating. Set ^20^7 to disable." },
	{ "cg_drawRealHeads", "Use original player head models (icon) . Set ^20^7 to disable." },
};


static const int cvarDescriptionTableSize = sizeof(cvarDescriptionTable) / sizeof(cvarDescriptionTable[0]);

void CG_RegisterCvarDescriptions(void)
{
	int i;
	for (i = 0; i < cvarDescriptionTableSize; i++)
	{
		if (cvarDescriptionTable[i].description && cvarDescriptionTable[i].description[0])
		{
			CG_SetCvarDescription(cvarDescriptionTable[i].cvarName, cvarDescriptionTable[i].description);
		}
	}
}
