/* SPDX-License-Identifier: GPL-2.0
 * The Original Code is Copyright (C) 2017-2024 by the baseq3a project with permission from the author. All rights reserved. */

#ifdef EXTERN_CG_CVAR
	#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags ) extern vmCvar_t vmCvar;
#endif

#ifdef DECLARE_CG_CVAR
	#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags ) vmCvar_t vmCvar;
#endif

#ifdef CG_CVAR_LIST
	#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags ) { & vmCvar, cvarName, defaultString, cvarFlags },
#endif

CG_CVAR( osp_hidden, "osp_print_issues", "0", CVAR_ARCHIVE )
CG_CVAR( osp_debug, "osp_debug", "0", CVAR_ARCHIVE )
CG_CVAR( cg_autoswitch, "cg_autoswitch", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawGun, "cg_drawGun", "1", CVAR_ARCHIVE )
CG_CVAR( cg_zoomFov, "cg_zoomfov", "22.5", CVAR_ARCHIVE )
CG_CVAR( cg_zoomTime, "cg_zoomTime", "150", CVAR_ARCHIVE )
CG_CVAR( cg_zoomSensitivityAuto, "cg_zoomSensitivityAuto", "1", CVAR_ARCHIVE )
CG_CVAR( cg_zoomSensitivityMultiplier, "cg_zoomSensitivityMultiplier", "0.1", CVAR_ARCHIVE )
CG_CVAR( cg_fov, "cg_fov", "90", CVAR_ARCHIVE )
CG_CVAR( cg_viewsize, "cg_viewsize", "100", CVAR_ARCHIVE )
CG_CVAR( cg_stereoSeparation, "cg_stereoSeparation", "0.4", CVAR_ARCHIVE )
CG_CVAR( cg_draw2D, "cg_draw2D", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawStatus, "cg_drawStatus", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawTimer, "cg_drawTimer", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawFPS, "cg_drawFPS", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawSnapshot, "cg_drawSnapshot", "0", CVAR_ARCHIVE )
CG_CVAR( cg_draw3dIcons, "cg_draw3dIcons", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawIcons, "cg_drawIcons", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawAttacker, "cg_drawAttacker", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshair, "cg_drawCrosshair", "16", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairGauntlet, "cg_drawCrosshairGauntlet", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairMachinegun, "cg_drawCrosshairMachinegun", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairShotgun, "cg_drawCrosshairShotgun", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairGrenadeLauncher, "cg_drawCrosshairGrenadeLauncher", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairRocketLauncher, "cg_drawCrosshairRocketLauncher", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairLightning, "cg_drawCrosshairLightning", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairRailgun, "cg_drawCrosshairRailgun", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairPlasmagun, "cg_drawCrosshairPlasmagun", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairBFG, "cg_drawCrosshairBFG", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairSize, "cg_crosshairSize", "24", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairAspectRatioFix, "cg_crosshairAspectRatioFix", "1", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairHealth, "cg_crosshairHealth", "0", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairX, "cg_crosshairX", "0", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairY, "cg_crosshairY", "0", CVAR_ARCHIVE )
CG_CVAR( cg_brassTime, "cg_brassTime", "2500", CVAR_ARCHIVE )
CG_CVAR( cg_simpleItems, "cg_simpleItems", "0", CVAR_ARCHIVE )
CG_CVAR( cg_addMarks, "cg_marks", "1", CVAR_ARCHIVE )
CG_CVAR( cg_lagometer, "cg_lagometer", "1", CVAR_ARCHIVE )
CG_CVAR( cg_railTrailTime, "cg_railTrailTime", "400", CVAR_ARCHIVE )
CG_CVAR( cg_gun_x, "cg_gunX", "0", CVAR_ARCHIVE )
CG_CVAR( cg_gun_y, "cg_gunY", "0", CVAR_ARCHIVE )
CG_CVAR( cg_gun_z, "cg_gunZ", "0", CVAR_ARCHIVE )
CG_CVAR( cg_centertime, "cg_centertime", "3", CVAR_CHEAT )
CG_CVAR( cg_runpitch, "cg_runpitch", "0.000", CVAR_ARCHIVE )
CG_CVAR( cg_runroll, "cg_runroll", "0.000", CVAR_ARCHIVE )
CG_CVAR( cg_bobup, "cg_bobup", "0.000", CVAR_ARCHIVE )
CG_CVAR( cg_bobpitch, "cg_bobpitch", "0.000", CVAR_ARCHIVE )
CG_CVAR( cg_bobroll, "cg_bobroll", "0.000", CVAR_ARCHIVE )
CG_CVAR( cg_swingSpeed, "cg_swingSpeed", "0.3", CVAR_CHEAT )
CG_CVAR( cg_animSpeed, "cg_animspeed", "1", CVAR_CHEAT )
CG_CVAR( cg_debugAnim, "cg_debuganim", "0", CVAR_CHEAT )
CG_CVAR( cg_debugPosition, "cg_debugposition", "0", CVAR_CHEAT )
CG_CVAR( cg_debugEvents, "cg_debugevents", "0", CVAR_CHEAT )
CG_CVAR( cg_errorDecay, "cg_errordecay", "100", 0 )
CG_CVAR( cg_nopredict, "cg_nopredict", "0", 0 )
CG_CVAR( cg_noPlayerAnims, "cg_noplayeranims", "0", CVAR_CHEAT )
CG_CVAR( cg_showmiss, "cg_showmiss", "0", 0 )
CG_CVAR( cg_footsteps, "cg_footsteps", "1", CVAR_CHEAT )
CG_CVAR( cg_tracerChance, "cg_tracerchance", "0.4", CVAR_CHEAT )
CG_CVAR( cg_tracerWidth, "cg_tracerwidth", "1", CVAR_CHEAT )
CG_CVAR( cg_tracerLength, "cg_tracerlength", "100", CVAR_CHEAT )
CG_CVAR( cg_thirdPersonRange, "cg_thirdPersonRange", "40", CVAR_CHEAT )
CG_CVAR( cg_thirdPersonAngle, "cg_thirdPersonAngle", "0", CVAR_CHEAT )
CG_CVAR( cg_thirdPerson, "cg_thirdPerson", "0", 0 )
CG_CVAR( cg_teamChatTime, "cg_teamChatTime", "3000", CVAR_ARCHIVE )
CG_CVAR( cg_teamChatHeight, "cg_teamChatHeight", "0", CVAR_ARCHIVE )
CG_CVAR( cg_forceModel, "cg_forceModel", "0", CVAR_ARCHIVE )
CG_CVAR( cg_predictItems, "cg_predictItems", "1", CVAR_ARCHIVE )
CG_CVAR( cg_deferPlayers, "cg_deferPlayers", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawTeamOverlay, "cg_drawTeamOverlay", "0", CVAR_ARCHIVE )
CG_CVAR( teamoverlay, "teamoverlay", "0", CVAR_USERINFO | CVAR_ROM )
CG_CVAR( cg_stats, "cg_stats", "0", 0 )
CG_CVAR( cg_buildScript, "com_buildScript", "0", 0 )
CG_CVAR( cg_paused, "cl_paused", "0", CVAR_ROM )
CG_CVAR( com_blood, "com_blood", "1", CVAR_ARCHIVE )
CG_CVAR( cg_synchronousClients, "g_synchronousClients", "0", 0 )
CG_CVAR( cg_cameraOrbit, "cg_cameraOrbit", "0", CVAR_CHEAT )
CG_CVAR( cg_cameraOrbitDelay, "cg_cameraOrbitDelay", "50", CVAR_ARCHIVE )
CG_CVAR( cg_timescaleFadeEnd, "cg_timescaleFadeEnd", "1", 0 )
CG_CVAR( cg_timescaleFadeSpeed, "cg_timescaleFadeSpeed", "0", 0 )
CG_CVAR( cg_timescale, "timescale", "1", 0 )
CG_CVAR( cg_scorePlums, "cg_scorePlums", "1", CVAR_ARCHIVE | CVAR_USERINFO )
CG_CVAR( cg_smoothClients, "cg_smoothClients", "0", CVAR_ARCHIVE | CVAR_USERINFO )
CG_CVAR( cg_cameraMode, "com_cameraMode", "0", CVAR_CHEAT )
CG_CVAR( pmove_fixed, "pmove_fixed", "0", 0 )
CG_CVAR( pmove_msec, "pmove_msec", "8", 0 )
CG_CVAR( cg_noTaunt, "cg_noTaunt", "0", CVAR_ARCHIVE )
CG_CVAR( cg_noProjectileTrail, "cg_noProjectileTrail", "0", CVAR_ARCHIVE )
CG_CVAR( cg_oldRail, "cg_oldRail", "1", CVAR_ARCHIVE )
CG_CVAR( cg_oldRocket, "cg_oldRocket", "1", CVAR_ARCHIVE )
CG_CVAR( cg_oldPlasma, "cg_oldPlasma", "1", CVAR_ARCHIVE )
CG_CVAR( cg_altGrenades, "cg_altGrenades", "0", CVAR_ARCHIVE )
CG_CVAR( cg_altLightning, "cg_altLightning", "0", CVAR_ARCHIVE )
CG_CVAR( cg_ammoCheck, "cg_ammoCheck", "0", CVAR_ARCHIVE )
CG_CVAR( cg_autoAction, "cg_autoAction", "0", CVAR_ARCHIVE )
CG_CVAR( cg_clientLog, "cg_clientLog", "0", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairPulse, "cg_crosshairPulse", "0", CVAR_ARCHIVE )
CG_CVAR( cg_customLoc, "cg_customLoc", "0", CVAR_ARCHIVE | CVAR_LATCH )
CG_CVAR( cg_damageSound, "cg_damageSound", "0", CVAR_ARCHIVE )
CG_CVAR( cg_damageDraw, "cg_damageDraw", "1", CVAR_ARCHIVE )
CG_CVAR( cg_damageIndicatorScale, "cg_damageIndicatorScale", "1.0", CVAR_ARCHIVE )
CG_CVAR( cg_damageIndicatorOpaque, "cg_damageIndicatorOpaque", "0", CVAR_ARCHIVE )
CG_CVAR( cg_damageKick, "cg_damageKick", "0", CVAR_ARCHIVE )
CG_CVAR( cg_deadBodyFilter, "cg_deadBodyFilter", "0", CVAR_ARCHIVE )
CG_CVAR( cg_deadBodyInvisible, "cg_deadBodyInvisible", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawDecals, "cg_drawDecals", "1", CVAR_ARCHIVE | CVAR_LATCH )
CG_CVAR( cg_drawPing, "cg_drawPing", "0", CVAR_ARCHIVE )
CG_CVAR( cg_enableOSPHUD, "cg_enableOSPHUD", "1", CVAR_ARCHIVE )
CG_CVAR( cg_shud, "cg_shud", "1", CVAR_ARCHIVE )
CG_CVAR( cg_enableBreath, "cg_enableBreath", "1", CVAR_ARCHIVE )
CG_CVAR( cg_enemyColors, "cg_enemyColors", "0", CVAR_ARCHIVE )
CG_CVAR( cg_enemyModel, "cg_enemyModel", "", CVAR_ARCHIVE )
CG_CVAR( cg_teamColors, "cg_teamColors", "0", CVAR_ARCHIVE )
CG_CVAR( cg_teamModel, "cg_teamModel", "", CVAR_ARCHIVE )
CG_CVAR( cg_execVstr, "cg_execVstr", "", CVAR_ARCHIVE )
CG_CVAR( cg_fallKick, "cg_fallKick", "0", CVAR_ARCHIVE )
CG_CVAR( cg_followkiller, "cg_followkiller", "0", CVAR_ARCHIVE )
CG_CVAR( cg_followpowerup, "cg_followpowerup", "0", CVAR_ARCHIVE )
CG_CVAR( cg_followviewcam, "cg_followviewcam", "1", CVAR_ARCHIVE )
CG_CVAR( cg_forceColors, "cg_forceColors", "0", CVAR_ARCHIVE )
CG_CVAR( cg_lightningImpact, "cg_lightningImpact", "0", CVAR_ARCHIVE )
CG_CVAR( cg_MaxlocationWidth, "cg_MaxlocationWidth", "16", CVAR_ARCHIVE )
CG_CVAR( cg_muzzleFlash, "cg_muzzleFlash", "1", CVAR_ARCHIVE )
CG_CVAR( cg_nochatbeep, "cg_noChatBeep", "0", CVAR_ARCHIVE )
CG_CVAR( cg_noTeamChatBeep, "cg_noTeamChatBeep", "0", CVAR_ARCHIVE )
CG_CVAR( cg_NoMOTDDisplayDuringDemo, "cg_NoMOTDDisplayDuringDemo", "0", CVAR_ARCHIVE )
CG_CVAR( cg_nomip, "cg_nomip", "0", CVAR_ARCHIVE )
CG_CVAR( cg_oversampleMouse, "cg_oversampleMouse", "0", CVAR_ARCHIVE )
CG_CVAR( cg_statScrollTime, "cg_statScrollTime", "0.15", CVAR_ARCHIVE )
CG_CVAR( cg_q3compScoreboard, "cg_q3compScoreboard", "1", CVAR_ARCHIVE )
CG_CVAR( cg_scoreTransparency, "cg_scoreTransparency", "1.0", CVAR_ARCHIVE )
CG_CVAR( cg_showPlayerLean, "cg_showPlayerLean", "1", CVAR_ARCHIVE )
CG_CVAR( cg_smoke_sg, "cg_smoke_sg", "1", CVAR_ARCHIVE )
CG_CVAR( cg_smokegrowth_gl, "cg_smokegrowth_gl", "1", CVAR_ARCHIVE )
CG_CVAR( cg_smokegrowth_rl, "cg_smokegrowth_rl", "1", CVAR_ARCHIVE )
CG_CVAR( cg_smokeradius_gl, "cg_smokeradius_gl", "32", CVAR_ARCHIVE )
CG_CVAR( cg_smokeradius_rl, "cg_smokeradius_rl", "64", CVAR_ARCHIVE )
CG_CVAR( cg_smokedensity_gl, "cg_smokedensity_gl", "50", CVAR_ARCHIVE )
CG_CVAR( cg_smokedensity_rl, "cg_smokedensity_rl", "50", CVAR_ARCHIVE )
CG_CVAR( cg_swapSkins, "cg_swapSkins", "0", 0 )
CG_CVAR( cg_teamRails, "cg_teamRails", "0", CVAR_ARCHIVE )
CG_CVAR( cg_trueLightning, "cg_trueLightning", "1.0", CVAR_ARCHIVE )
CG_CVAR( cg_useScreenShotJPEG, "cg_useScreenShotJPEG", "0", CVAR_ARCHIVE )
CG_CVAR( ch_3waveFont, "ch_3waveFont", "0", CVAR_ARCHIVE )
CG_CVAR( ch_ColorLocations, "ch_ColorLocations", "1", CVAR_ARCHIVE )
CG_CVAR( ch_CrosshairColor, "ch_crosshairColor", "White", CVAR_ARCHIVE )
CG_CVAR( cf_CrosshairNames, "cf_CrosshairNames", "12x12", CVAR_ARCHIVE )
CG_CVAR( ch_CrosshairNamesLeft, "ch_CrosshairNamesLeft", "0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairTeamInfo, "ch_crosshairTeamInfo", "1", CVAR_ARCHIVE )
CG_CVAR( ch_drawHealthMeters, "ch_drawHealthMeters", "0", CVAR_ARCHIVE )
CG_CVAR( ch_drawFlagNames, "ch_drawFlagNames", "2", CVAR_ARCHIVE )
CG_CVAR( ch_drawPickup, "ch_drawPickup", "1", CVAR_ARCHIVE )
CG_CVAR( ch_drawSpeed, "ch_drawSpeed", "0", CVAR_ARCHIVE )
CG_CVAR( ch_TeamBackground, "ch_TeamBackground", "0", CVAR_ARCHIVE )
CG_CVAR( cf_Following, "cf_Following", "24x24", CVAR_ARCHIVE )
CG_CVAR( ch_FilterLocationsTeamchat, "ch_FilterLocationsTeamchat", "0", CVAR_ARCHIVE )
CG_CVAR( ch_fragMessage, "ch_fragMessage", "1", CVAR_ARCHIVE )
CG_CVAR( ch_file, "ch_file", "default", CVAR_ARCHIVE )
CG_CVAR( cf_Fragmsg, "cf_Fragmsg", "16x16", CVAR_ARCHIVE )
CG_CVAR( ch_graphs, "ch_graphs", "1", CVAR_ARCHIVE )
CG_CVAR( ch_InverseTeamChat, "ch_InverseTeamChat", "1", CVAR_ARCHIVE )
CG_CVAR( ch_Obituaries, "ch_Obituaries", "1", CVAR_ARCHIVE )
CG_CVAR( ch_Pickupitem, "ch_Pickupitem", "1", CVAR_ARCHIVE )
CG_CVAR( cf_Pickupstring, "cf_Pickupstring", "10x14", CVAR_ARCHIVE )
CG_CVAR( ch_recordMessage, "ch_recordMessage", "1", CVAR_ARCHIVE )
CG_CVAR( cf_Scores, "cf_Scores", "16x16", CVAR_ARCHIVE )
CG_CVAR( cf_Statusbar, "cf_Statusbar", "32x32", CVAR_ARCHIVE )
CG_CVAR( ch_StatusbarFormat, "ch_StatusbarFormat", "10", CVAR_ARCHIVE )
CG_CVAR( ch_statusbarStyle, "ch_statusbarStyle", "1", CVAR_ARCHIVE )
CG_CVAR( ch_teamBackground, "ch_teamBackground", "1", CVAR_ARCHIVE )
CG_CVAR( cf_Teamchat, "cf_Teamchat", "8x12", CVAR_ARCHIVE )
CG_CVAR( ch_TeamchatOnly, "ch_TeamchatOnly", "0", CVAR_ARCHIVE )
CG_CVAR( ch_TeamCrosshairHealth, "ch_TeamCrosshairHealth", "1", CVAR_ARCHIVE )
CG_CVAR( cf_TeamCrosshairHealth, "cf_TeamCrosshairHealth", "12x12", CVAR_ARCHIVE )
CG_CVAR( ch_Teamoverlay, "ch_Teamoverlay", "p12n h/aw l", CVAR_ARCHIVE )
CG_CVAR( cf_Teamoverlay, "cf_Teamoverlay", "6x11", CVAR_ARCHIVE )
CG_CVAR( cf_Vote, "cf_Vote", "10x14", CVAR_ARCHIVE )
CG_CVAR( ch_weaponList, "ch_weaponList", "1", CVAR_ARCHIVE )
CG_CVAR( ch_weaponListBackground, "ch_weaponListBackground", "1", CVAR_ARCHIVE )
CG_CVAR( ch_weaponListDrawAll, "ch_weaponListDrawAll", "0", CVAR_ARCHIVE )
CG_CVAR( ch_weaponListFlash, "ch_weaponListFlash", "1", CVAR_ARCHIVE )
CG_CVAR( ch_Weaponswitch, "ch_Weaponswitch", "4", CVAR_ARCHIVE )
CG_CVAR( cf_WeaponSwitch, "cf_WeaponSwitch", "32x32", CVAR_ARCHIVE )
CG_CVAR( cf_WeaponName, "cf_WeaponName", "12x12", CVAR_ARCHIVE )
CG_CVAR( cf_AmmoStatusbar, "cf_AmmoStatusbar", "8x8", CVAR_ARCHIVE )
CG_CVAR( cf_timer, "cf_timer", "16x16", CVAR_ARCHIVE )
CG_CVAR( s_ambient, "s_ambient", "1", CVAR_ARCHIVE )
CG_CVAR( cl_maxpackets, "cl_maxpackets", "30", CVAR_ARCHIVE )
CG_CVAR( cl_timenudge, "cl_timenudge", "0", CVAR_ARCHIVE )
CG_CVAR( snaps, "snaps", "40", CVAR_ARCHIVE )
CG_CVAR( r_shownormals, "r_shownormals", "0", CVAR_LATCH | CVAR_CHEAT )
CG_CVAR( r_fullbright, "r_fullbright", "0", CVAR_LATCH )
CG_CVAR( r_lodCurveError, "r_lodCurveError", "250", CVAR_LATCH )
CG_CVAR( r_showtris, "r_showtris", "0", 0 )
CG_CVAR( r_subdivisions, "r_subdivisions", "4", CVAR_LATCH )
CG_CVAR( r_znear, "r_znear", "4", 0 )
CG_CVAR( handicap, "handicap", "100", 0 )
CG_CVAR( m_pitch, "m_pitch", "0.022", CVAR_ARCHIVE )
CG_CVAR( com_maxfps, "com_maxfps", "125", CVAR_ARCHIVE )
CG_CVAR( cg_gun_frame, "", "0", CVAR_ARCHIVE )
CG_CVAR( cg_noLeadSounds, "cg_noLeadSounds", "0", CVAR_ARCHIVE )
CG_CVAR( cg_fragSound, "cg_fragSound", "1", CVAR_ARCHIVE )
CG_CVAR( cg_lightningHideCrosshair, "cg_lightningHideCrosshair", "0", CVAR_ARCHIVE )
CG_CVAR( cg_lightningSilent, "cg_lightningSilent", "0", CVAR_ARCHIVE )
CG_CVAR( cg_lightningHide, "cg_lightningHide", "0", CVAR_ARCHIVE )
CG_CVAR( cg_delag, "cg_delag", "4", CVAR_ARCHIVE )
CG_CVAR( cg_projectileNudge, "cg_projectileNudge", "3", CVAR_ARCHIVE )
CG_CVAR( cg_hideScores, "cg_hideScores", "0", CVAR_ARCHIVE )
CG_CVAR( cg_deadBodyBlack, "cg_deadBodyBlack", "1", CVAR_ARCHIVE )
CG_CVAR( cg_spectGlow, "cg_spectGlow", "0", CVAR_ARCHIVE )
CG_CVAR( cg_spectOrigModel, "cg_spectOrigModel", "0", CVAR_ARCHIVE )
CG_CVAR( cg_hitSounds, "cg_hitSounds", "1", CVAR_ARCHIVE )
CG_CVAR( cg_playersXID, "cg_playersXID", "0", CVAR_ARCHIVE )
CG_CVAR( cg_playersID, "cg_playersID", "0", CVAR_ARCHIVE )
CG_CVAR( cg_playerModelColors, "cg_playerModelColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_playerRailColors, "cg_playerRailColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_playerFrozenColor, "cg_playerFrozenColor", "", CVAR_ARCHIVE )
CG_CVAR( cg_teamModelColors, "cg_teamModelColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_teamRailColors, "cg_teamRailColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_teamFrozenColor, "cg_teamFrozenColor", "", CVAR_ARCHIVE )
CG_CVAR( cg_enemyModelColors, "cg_enemyModelColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_enemyRailColors, "cg_enemyRailColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_enemyFrozenColor, "cg_enemyFrozenColor", "", CVAR_ARCHIVE )
CG_CVAR( cg_enemyModelColorsUnique, "cg_enemyModelColorsUnique", "1", CVAR_ARCHIVE )
CG_CVAR( cg_teamFrozenFoe, "cg_teamFrozenFoe", "1", CVAR_ARCHIVE )
CG_CVAR( cg_chatEnable, "cg_chatEnable", "3", CVAR_ARCHIVE )
CG_CVAR( cg_shudChatEnable, "cg_shudChatEnable", "3", CVAR_ARCHIVE )
CG_CVAR( cg_healthMid, "cg_healthMid", "200", CVAR_ARCHIVE )
CG_CVAR( cg_healthLow, "cg_healthLow", "100", CVAR_ARCHIVE )
CG_CVAR( cg_healthColorLevels, "cg_healthColorLevels", "1", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecor, "ch_crosshairDecor", "0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorSize, "ch_crosshairDecorSize", "24", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorColor, "ch_crosshairDecorColor", "white", CVAR_ARCHIVE )
CG_CVAR( ch_crosshair45, "ch_crosshair45", "0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecor45, "ch_crosshairDecor45", "0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorOpaque, "ch_crosshairDecorOpaque", "0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairOpaque, "ch_crosshairOpaque", "0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairAction, "ch_crosshairAction", "0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairActionColor, "ch_crosshairActionColor", "red", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairActionScale, "ch_crosshairActionScale", "2.0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairActionTime, "ch_crosshairActionTime", "400", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorAction, "ch_crosshairDecorAction", "4", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorActionColor, "ch_crosshairDecorActionColor", "red", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorActionScale, "ch_crosshairDecorActionScale", "2.0", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorActionTime, "ch_crosshairDecorActionTime", "400", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairAutoScale, "ch_crosshairAutoScale", "1", CVAR_ARCHIVE )
CG_CVAR( cg_dlightGauntlet, "cg_dlightGauntlet", "9999FF", CVAR_ARCHIVE )
CG_CVAR( cg_dlightMG, "cg_dlightMG", "FFFF00", CVAR_ARCHIVE )
CG_CVAR( cg_dlightSG, "cg_dlightSG", "FFFF00", CVAR_ARCHIVE )
CG_CVAR( cg_dlightGL, "cg_dlightGL", "FFBF00", CVAR_ARCHIVE )
CG_CVAR( cg_dlightRL, "cg_dlightRL", "FFBF00", CVAR_ARCHIVE )
CG_CVAR( cg_dlightLG, "cg_dlightLG", "9999FF", CVAR_ARCHIVE )
CG_CVAR( cg_dlightRG, "cg_dlightRG", "FF8000", CVAR_ARCHIVE )
CG_CVAR( cg_dlightPG, "cg_dlightPG", "9999FF", CVAR_ARCHIVE )
CG_CVAR( cg_dlightBFG, "cg_dlightBFG", "FFB2FF", CVAR_ARCHIVE )
CG_CVAR( cg_gunColor, "cg_gunColor", "White", CVAR_ARCHIVE )
CG_CVAR( cg_gunOpaque, "cg_gunOpaque", "0.15", CVAR_ARCHIVE )
CG_CVAR( cg_drawBrightWeapons, "cg_drawBrightWeapons", "0", CVAR_ARCHIVE )
CG_CVAR( cg_conObituaries, "cg_conObituaries", "1", CVAR_ARCHIVE )
CG_CVAR( cg_lightningHitsoundRateFix, "cg_lightningHitsoundRateFix", "1", CVAR_ARCHIVE )
CG_CVAR( cg_stackHitSounds, "cg_stackHitSounds", "1", CVAR_ARCHIVE )
CG_CVAR( cg_stackHitSoundsTimeout, "cg_stackHitSoundsTimeout", "500", CVAR_ARCHIVE )
CG_CVAR( cg_drawCenterMessages, "cg_drawCenterMessages", "1", CVAR_ARCHIVE )
CG_CVAR( cg_predictStepOffset, "cg_predictStepOffset", "1", CVAR_ARCHIVE )
CG_CVAR( cg_enemyLightningColor, "cg_enemyLightningColor", "0", CVAR_ARCHIVE )
CG_CVAR( cg_uniqueColorTable, "cg_uniqueColorTable", "1", CVAR_ARCHIVE )
CG_CVAR( cg_noVoteBeep, "cg_noVoteBeep", "0", CVAR_ARCHIVE )
CG_CVAR( cg_damageDrawFrame, "cg_damageDrawFrame", "2", CVAR_ARCHIVE )
CG_CVAR( cg_damageFrameSize, "cg_damageFrameSize", "2", CVAR_ARCHIVE )
CG_CVAR( cg_damageFrameOpaque, "cg_damageFrameOpaque", "0.65", CVAR_ARCHIVE )
CG_CVAR( cg_shud_currentWeapons, "cg_shud_currentWeapons", "226", CVAR_ARCHIVE )
CG_CVAR( cg_drawHitBox, "cg_drawHitBox", "0", CVAR_ARCHIVE )
CG_CVAR( cg_hitBoxColor, "cg_hitBoxColor", "004444", CVAR_ARCHIVE )
CG_CVAR( cg_drawGunForceAspect, "cg_drawGunForceAspect", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawOutline, "cg_drawOutline", "3", CVAR_ARCHIVE )
CG_CVAR( cg_enemyOutlineSize, "cg_enemyOutlineSize", "1", CVAR_ARCHIVE )
CG_CVAR( cg_enemyOutlineColor, "cg_enemyOutlineColor", "Magenta", CVAR_ARCHIVE )
CG_CVAR( cg_enemyOutlineColorUnique, "cg_enemyOutlineColorUnique", "0", CVAR_ARCHIVE )
CG_CVAR( cg_teamOutlineSize, "cg_teamOutlineSize", "1", CVAR_ARCHIVE )
CG_CVAR( cg_teamOutlineColor, "cg_teamOutlineColor", "Yellow", CVAR_ARCHIVE )
CG_CVAR( cg_underwaterFovWarp, "cg_underwaterFovWarp", "1", CVAR_ARCHIVE )
CG_CVAR( cg_altBlood, "cg_altBlood", "0", CVAR_ARCHIVE )
CG_CVAR( cg_altBloodColor, "cg_altBloodColor", "White", CVAR_ARCHIVE )
CG_CVAR( cg_altPlasma, "cg_altPlasma", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawRewards, "cg_drawRewards", "1", CVAR_ARCHIVE )
CG_CVAR( cg_shotGunTracer, "cg_shotGunTracer", "1", CVAR_ARCHIVE )
CG_CVAR( cg_railRingsRadius, "cg_railRingsRadius", "4.0", CVAR_ARCHIVE )
CG_CVAR( cg_railRingsRotation, "cg_railRingsRotation", "1", CVAR_ARCHIVE )
CG_CVAR( cg_railRingsSpacing, "cg_railRingsSpacing", "5", CVAR_ARCHIVE )
CG_CVAR( cg_railRingsSize, "cg_railRingsSize", "1.1", CVAR_ARCHIVE )
CG_CVAR( cg_railStaticRings, "cg_railStaticRings", "0", CVAR_ARCHIVE )
CG_CVAR( cg_gunPos, "cg_gunPos", "1", CVAR_ARCHIVE )
CG_CVAR( cg_shadows, "cg_shadows", "1", CVAR_ARCHIVE )
CG_CVAR( cg_altShadow, "cg_altShadow", "0", CVAR_ARCHIVE )
CG_CVAR( cg_altShadowColor, "cg_altShadowColor", "White", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardShowId, "cg_scoreboardShowId", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawFriend, "cg_drawFriend", "1", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicator, "cg_teamIndicator", "14", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorAdjust, "cg_teamIndicatorAdjust", "1", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorColor, "cg_teamIndicatorColor", "White", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorOpaque, "cg_teamIndicatorOpaque", "1", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorBgColor, "cg_teamIndicatorBgColor", "444444", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorBgOpaque, "cg_teamIndicatorBgOpaque", "0.4", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorOffset, "cg_teamIndicatorOffset", "12", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorMaxLength, "cg_teamIndicatorMaxLength", "13", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorFont, "cg_teamIndicatorFont", "4", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardBE, "cg_scoreboardBE", "0", CVAR_ARCHIVE | CVAR_UPDATED )
CG_CVAR( cg_scoreboardFont, "cg_scoreboardFont", "2", CVAR_ARCHIVE )
CG_CVAR( cg_centerMessagesFont, "cg_centerMessagesFont", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairNames, "cg_drawCrosshairNames", "1", CVAR_ARCHIVE )
CG_CVAR( cg_railCustomChamber, "cg_railCustomChamber", "1", CVAR_ARCHIVE )
CG_CVAR( cg_altGrenadesColor, "cg_altGrenadesColor", "7", CVAR_ARCHIVE )
CG_CVAR( cg_enemyGrenadesColor, "cg_enemyGrenadesColor", "2", CVAR_ARCHIVE )
CG_CVAR( cg_altBattleSuit, "cg_altBattleSuit", "0", CVAR_ARCHIVE )
CG_CVAR( cg_itemFx, "cg_itemFx", "7", CVAR_ARCHIVE )
CG_CVAR( cg_bubbleTrail, "cg_bubbleTrail", "1", CVAR_ARCHIVE )
CG_CVAR( cg_gibs, "cg_gibs", "1", CVAR_ARCHIVE )
CG_CVAR( cg_ignoreServerMessages, "cg_ignoreServerMessages", "0", CVAR_ARCHIVE )
CG_CVAR( cg_drawAmmoWarning, "cg_drawAmmoWarning", "1", CVAR_ARCHIVE )
CG_CVAR( cg_healthColor, "cg_healthColor", "Yellow", CVAR_ARCHIVE )
CG_CVAR( cg_healthLowColor, "cg_healthLowColor", "Red", CVAR_ARCHIVE )
CG_CVAR( cg_healthMidColor, "cg_healthMidColor", "White", CVAR_ARCHIVE )
CG_CVAR( cg_redTeamColor, "cg_redTeamColor", "Red", CVAR_ARCHIVE )
CG_CVAR( cg_blueTeamColor, "cg_blueTeamColor", "Blue", CVAR_ARCHIVE )
CG_CVAR( cg_friendHudMarkerMaxDist, "cg_friendHudMarkerMaxDist", "0", CVAR_ARCHIVE )
CG_CVAR( cg_friendHudMarkerSize, "cg_friendHudMarkerSize", "1.75", CVAR_ARCHIVE )
CG_CVAR( cg_friendHudMarkerMaxScale, "cg_friendHudMarkerMaxScale", "0.5", CVAR_ARCHIVE )
CG_CVAR( cg_friendHudMarkerMinScale, "cg_friendHudMarkerMinScale", "0.0", CVAR_ARCHIVE )
CG_CVAR( cg_friendsWallhack, "cg_friendsWallhack", "1", CVAR_ARCHIVE | CVAR_UPDATED )
CG_CVAR( cg_drawHudMarkers, "cg_drawHudMarkers", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawAccuracy, "cg_drawAccuracy", "4", CVAR_ARCHIVE )
CG_CVAR( cg_accuracyFontSize, "cg_accuracyFontSize", "12", CVAR_ARCHIVE )
CG_CVAR( cg_accuracyIconSize, "cg_accuracyIconSize", "18", CVAR_ARCHIVE )
CG_CVAR( cg_accuracyFont, "cg_accuracyFont", "2", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairActionColorLow, "ch_crosshairActionColorLow", "white", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairActionColorMid, "ch_crosshairActionColorMid", "yellow", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairActionColorHigh, "ch_crosshairActionColorHigh", "orange", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorActionColorLow, "ch_crosshairDecorActionColorLow", "white", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorActionColorMid, "ch_crosshairDecorActionColorMid", "yellow", CVAR_ARCHIVE )
CG_CVAR( ch_crosshairDecorActionColorHigh, "ch_crosshairDecorActionColorHigh", "orange", CVAR_ARCHIVE )
CG_CVAR( cg_markTeam, "cg_markTeam", "-1", CVAR_ARCHIVE )
CG_CVAR( cg_markTeamColor, "cg_markTeamColor", "Pink", CVAR_ARCHIVE )
CG_CVAR( cg_mySound, "cg_mySound", "", CVAR_ARCHIVE | CVAR_LATCH )
CG_CVAR( cg_teamSound, "cg_teamSound", "", CVAR_ARCHIVE | CVAR_LATCH )
CG_CVAR( cg_enemySound, "cg_enemySound", "", CVAR_ARCHIVE | CVAR_LATCH )
CG_CVAR( cg_scoreboardRtColors, "cg_scoreboardRtColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardBtColors, "cg_scoreboardBtColors", "", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardSpecColor, "cg_scoreboardSpecColor", "", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardDrawPowerUps, "cg_scoreboardDrawPowerUps", "1", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_style, "cg_bestats_style", "1", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_textSize, "cg_bestats_textSize", "6 8", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_font, "cg_bestats_font", "2", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_pos, "cg_bestats_pos", "4 320", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_bgColor, "cg_bestats_bgColor", "", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_bgOpaque, "cg_bestats_bgOpaque", "0.7", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_spacingAdjust, "cg_bestats_spacingAdjust", "1", CVAR_ARCHIVE )
CG_CVAR( cg_bestats_widthCutoff, "cg_bestats_widthCutoff", "2", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorFade, "cg_teamIndicatorFade", "0.75", CVAR_ARCHIVE )
CG_CVAR( cg_teamIndicatorFadeRadius, "cg_teamIndicatorFadeRadius", "128", CVAR_ARCHIVE )
CG_CVAR( be_features, "be_features", "", CVAR_USERINFO | CVAR_ROM )
CG_CVAR( be_enabled, "be_enabled", "1", CVAR_ARCHIVE | CVAR_USERINFO | CVAR_NEW )
CG_CVAR( chud_file, "chud_file", "default.cfg", CVAR_ARCHIVE | CVAR_NEW )
CG_CVAR( cg_chud, "cg_chud", "0", CVAR_ARCHIVE | CVAR_NEW )
CG_CVAR( cg_clearOnLevelLoad, "cg_clearOnLevelLoad", "0", CVAR_ARCHIVE | CVAR_NEW )
CG_CVAR( cg_spectPOV, "cg_spectPOV", "0", CVAR_ARCHIVE | CVAR_NEW )
CG_CVAR( cg_drawRealHeads, "cg_drawRealHeads", "0", CVAR_ARCHIVE | CVAR_NEW )
CG_CVAR( be_run, "be_run", "0", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardTextSize, "cg_scoreboardTextSize", "14", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardScale, "cg_scoreboardScale", "1.0", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardWidth, "cg_scoreboardWidth", "640", CVAR_ARCHIVE )
CG_CVAR( cg_scoreboardColors, "cg_scoreboardColors", "", CVAR_ARCHIVE )
CG_CVAR( g_promode, "g_promode", "0", 0 )
CG_CVAR( osp_client, "osp_client", "1008_OSP2_"OSP_VERSION, CVAR_USERINFO | CVAR_ROM )
CG_CVAR( cg_flagStyle, "cg_flagStyle", "1", CVAR_ARCHIVE )
CG_CVAR( cg_flagPOIs,  "cg_flagPOIs",  "1", CVAR_ARCHIVE )

#undef CG_CVAR
